name: flutterdicas
description: Projeto Flutter Dicas

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter_native_splash: ^2.2.9
  flutter_launcher_icons: ^0.10.0
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/images/logo_no_white_space.png

flutter:
  uses-material-design: true

  assets:
    - assets/images/